#pragma once

#define SENSOR_MEASURE 0x01
#define SENSOR_CALIBRATION_START (0x01 << 1)
#define SENSOR_CALIBRATION_STOP (0x01 << 2)
#define SENSOR_LOAD_PARAMS (0x01 << 3)
#define SENSOR_DEBUG_EKF (0x01 << 4)

#define RADIORX_DEBUG_RADIO 0x01

#define TELEM_GET_RUNTIME_STATS (0x01 << 1)

#define MAV_CMD_REQUEST_RC 12
#define MAV_CMD_REQUEST_EKF 13
#define MAV_CMD_REQUEST_RUNTIME_STATS 14
