#pragma once

#define TASK_RADIORX_STACK_SIZE 1524U
#define TASK_LOGGING_STACK_SIZE 2048U
#define TASK_TELEM_STACK_SIZE 1024U
#define TASK_SENSOR_STACK_SIZE 2048U
#define TASK_FLIGHTLOOP_STACK_SIZE 256U
#define TASK_FAILSAFE_STACK_SIZE 256U
#define TASK_STARTUP_STACK_SIZE 0U
#define TASK_COMMRX_STACK_SIZE 1024U

#define TASK_RADIORX_PRIORITY 5
#define TASK_LOGGING_PRIORITY 7
#define TASK_TELEM_PRIORITY 3
#define TASK_SENSOR_PRIORITY 3
#define TASK_FLIGHTLOOP_PRIORITY 2
#define TASK_FAILSAFE_PRIORITY 1
#define TASK_STARTUP_PRIORITY 1
#define TASK_COMMRX_PRIORITY 6

#define ENABLE_RUNTIME_STATS 1

#define LOG_QUEUE_LEN 5

#define RADIORX_DMA_LEN 256
#define COMMRX_DMA_LEN 400

#define CRSF_BUFFER_SIZE 256
#define COMM_BUFFER_SIZE 256

#define RC_MAP_CH_ROLL 0
#define RC_MAP_CH_PITCH 1
#define RC_MAP_CH_YAW 2
#define RC_MAP_CH_THROTTLE 3
#define RC_MAP_CH_MODE 4
#define RC_MAP_CH_ARM 5

#define RC_ANGLE_MAX 30  // deg
#define RC_ANGLE_MIN -30 // deg
#define RC_VEL_MAX 15    // m/s
#define RC_VEL_MIN -15   // m/s
#define RC_VEL_RANGE (((float)RC_VEL_MAX - (float)RC_VEL_MIN))
#define RC_VEL_MID (((float)RC_VEL_MIN + (float)RC_VEL_MAX) / 2.0f)

#define HCSR04_SENSOR_COUNT 6
#define HCSR04_TRIG_PORT GPIOB
#define HCSR04_TRIG_PIN GPIO_PIN_12
#define HCSR04_BUFFER_LEN 3