#pragma once

#define TASK_RADIORX_STACK_SIZE 1524U
#define TASK_LOGGING_STACK_SIZE 2048U
#define TASK_TELEM_STACK_SIZE 1024U
#define TASK_SENSOR_STACK_SIZE 2048U
#define TASK_FLIGHTLOOP_STACK_SIZE 256U
#define TASK_FAILSAFE_STACK_SIZE 256U
#define TASK_STARTUP_STACK_SIZE 0U
#define TASK_COMMRX_STACK_SIZE 1024U

#define TASK_RADIORX_PRIORITY 5
#define TASK_LOGGING_PRIORITY 7
#define TASK_TELEM_PRIORITY 3
#define TASK_SENSOR_PRIORITY 3
#define TASK_FLIGHTLOOP_PRIORITY 2
#define TASK_FAILSAFE_PRIORITY 1
#define TASK_STARTUP_PRIORITY 1
#define TASK_COMMRX_PRIORITY 6

#define ENABLE_RUNTIME_STATS 1

#define LOG_QUEUE_LEN 10

#define RADIORX_DMA_LEN 256
#define COMMRX_DMA_LEN 400

#define CRSF_BUFFER_SIZE 256
#define COMM_BUFFER_SIZE 256
